version: '3.4'

services:

  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=powerapi_formula

  power-api-formula:
    image: powerapi/smartwatts-formula
    depends_on:
      - influxdb
    cap_add:
      - ALL
    volumes:
      - ./config-formula.json:/config-formula.json
    command:
      - "--config-file"
      - "/config-formula.json"
   
   
  
  power-api-sensor:
    image: powerapi/hwpc-sensor:latest
    depends_on:
      - influxdb
    cap_add:
      - ALL
    volumes:
      - ./config-sensor.json:/config-sensor.json
    command:
      - "--config-file"
      - "/config-sensor.json"
    